#### Java中，所有的异常都有一个共同的祖先java.lang包中的Throwable类。

**Throwable**：有两个重要的子类：Excepetion(异常）和Error(错误），二者都是Java异常处理的重要子类，各自都包含大量子类。

**Error**：程序无法处理的错误。表示运行应用程序中较严重的问题，大多数错误与代码编写者执行的操作无关，而代表代码运行时JVM出现的问题。例如：Java虚拟机运行错误（VirtualMachineError），当JVM不再有继续执行操作所需的内存资源时，将出现OutOfMemoryError。这些异常发生时，Java虚拟机一般选择线程终止。

**Exception**（异常）：是程序本身可以处理的异常。Exception类有一个重要的子类RuntimeException。RuntimeException异常由Java虚拟机抛出。
NullPointerException：要访问的变量没有引用任何对象时，抛出该异常。
ArithmeticException：算数运算异常，一个整数除以0时，抛出该异常。
ArrayIndexOutOfBoundsException：下标越界异常。

**注意：异常和错误的区别：异常能被程序本身处理，错误是无法处理。**


Throwable类常用方法：

* public string getMessage()：返回异常发生时的简要描述。
* public string toString()：返回异常发生时的详细信息。
* public string getLocalizedMessage()：返回异常对象的本地化信息。使用Throwable的子类覆盖这个方法，可以生成本地化信息。如果子类没有覆盖该方法，则该方法返回的信息与getMessage（）返回的结果相同。
* public void printStackTrace()：在控制台上打印Throwable对象封装的异常信息

**异常处理总结**：
try：用于捕获异常，其后可接0个或多个catch块，如果没有catch块，则必须跟一个finally块
catch：用于处理try捕获到的异常
finally：无论是否捕获或处理异常，finally块里的语句都会被执行。当在try块或catch块中遇到return语句时，finally语句块将在方法返回之前被执行。

**以下4中特殊情况下，finally块不会被执行：**
1. 在finally语句块第一行发生了异常。因为在其他行，finally块还是会得到执行
2. 在前面的代码中用了System.exit(int)已退出程序。exit是带参函数：若该语句在异常语句之后，finally会执行
3. 程序所在的线程死亡
4. 关闭CPU

